# Generated by Django 5.2 on 2025-07-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="students_photos/"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="age",
            field=models.PositiveIntegerField(),
        ),
    ]
