# Generated by Django 5.2 on 2025-07-08 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="classroom",
            options={
                "ordering": ["name", "section"],
                "verbose_name_plural": "Classrooms",
            },
        ),
        migrations.AlterModelOptions(
            name="notice",
            options={"ordering": ["-date_posted"]},
        ),
        migrations.AlterModelOptions(
            name="student",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="subject",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="teacher",
            options={"ordering": ["name"]},
        ),
    ]
