# Generated by Django 5.2 on 2025-07-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0002_classroom_description_alter_attendance_student_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classroom",
            name="description",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="classroom",
        ),
        migrations.AddField(
            model_name="classroom",
            name="subjects",
            field=models.ManyToManyField(
                blank=True, related_name="classrooms", to="school.subject"
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="code",
            field=models.CharField(default="GEN", max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="classroom",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="section",
            field=models.CharField(max_length=1),
        ),
    ]
